// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package ruledb

import (
	"context"

	"github.com/google/uuid"
)

const createRule = `-- name: CreateRule :one
INSERT INTO fine_rules (code, name, description, fine_amount, version, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, name, description, fine_amount, version, is_active, created_at, updated_at
`

type CreateRuleParams struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	FineAmount  float64 `json:"fine_amount"`
	Version     int32   `json:"version"`
	IsActive    bool    `json:"is_active"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (FineRule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.FineAmount,
		arg.Version,
		arg.IsActive,
	)
	var i FineRule
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.FineAmount,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateRuleVersions = `-- name: DeactivateRuleVersions :exec
UPDATE fine_rules
SET is_active = FALSE, updated_at = NOW()
WHERE code = $1 AND is_active = TRUE
`

func (q *Queries) DeactivateRuleVersions(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deactivateRuleVersions, code)
	return err
}

const getActiveRuleByCode = `-- name: GetActiveRuleByCode :one
SELECT id, code, name, description, fine_amount, version, is_active, created_at, updated_at
FROM fine_rules
WHERE code = $1 AND is_active = TRUE
`

func (q *Queries) GetActiveRuleByCode(ctx context.Context, code string) (FineRule, error) {
	row := q.db.QueryRow(ctx, getActiveRuleByCode, code)
	var i FineRule
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.FineAmount,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuleByCodeAndVersion = `-- name: GetRuleByCodeAndVersion :one
SELECT id, code, name, description, fine_amount, version, is_active, created_at, updated_at
FROM fine_rules
WHERE code = $1 AND version = $2
`

type GetRuleByCodeAndVersionParams struct {
	Code    string `json:"code"`
	Version int32  `json:"version"`
}

func (q *Queries) GetRuleByCodeAndVersion(ctx context.Context, arg GetRuleByCodeAndVersionParams) (FineRule, error) {
	row := q.db.QueryRow(ctx, getRuleByCodeAndVersion, arg.Code, arg.Version)
	var i FineRule
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.FineAmount,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuleByID = `-- name: GetRuleByID :one
SELECT id, code, name, description, fine_amount, version, is_active, created_at, updated_at
FROM fine_rules
WHERE id = $1
`

func (q *Queries) GetRuleByID(ctx context.Context, id uuid.UUID) (FineRule, error) {
	row := q.db.QueryRow(ctx, getRuleByID, id)
	var i FineRule
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.FineAmount,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRules = `-- name: ListActiveRules :many
SELECT id, code, name, description, fine_amount, version, is_active, created_at, updated_at
FROM fine_rules
WHERE is_active = TRUE
ORDER BY code ASC
`

func (q *Queries) ListActiveRules(ctx context.Context) ([]FineRule, error) {
	rows, err := q.db.Query(ctx, listActiveRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FineRule{}
	for rows.Next() {
		var i FineRule
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.FineAmount,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleVersions = `-- name: ListRuleVersions :many
SELECT id, code, name, description, fine_amount, version, is_active, created_at, updated_at
FROM fine_rules
WHERE code = $1
ORDER BY version DESC
`

func (q *Queries) ListRuleVersions(ctx context.Context, code string) ([]FineRule, error) {
	rows, err := q.db.Query(ctx, listRuleVersions, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FineRule{}
	for rows.Next() {
		var i FineRule
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.FineAmount,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
