// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package violationdb

import (
	"time"

	"github.com/google/uuid"
)

type FineRule struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	FineAmount  float64   `json:"fine_amount"`
	Version     int32     `json:"version"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Payment struct {
	ID            uuid.UUID `json:"id"`
	ViolationID   uuid.UUID `json:"violation_id"`
	Amount        float64   `json:"amount"`
	Status        string    `json:"status"`
	PaymentMethod string    `json:"payment_method"`
	ReferenceID   string    `json:"reference_id"`
	ErrorMessage  string    `json:"error_message"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Vehicle struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	PlateNumber string    `json:"plate_number"`
	CreatedAt   time.Time `json:"created_at"`
}

type Violation struct {
	ID          uuid.UUID `json:"id"`
	FineRuleID  uuid.UUID `json:"fine_rule_id"`
	PlateNumber string    `json:"plate_number"`
	OfficerID   uuid.UUID `json:"officer_id"`
	Status      string    `json:"status"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
