// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: violations.sql

package violationdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAllViolations = `-- name: CountAllViolations :one
SELECT COUNT(*)::bigint FROM violations
`

func (q *Queries) CountAllViolations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllViolations)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countViolationsByPlates = `-- name: CountViolationsByPlates :one
SELECT COUNT(*)::bigint 
FROM violations
WHERE plate_number = ANY($1::VARCHAR[])
`

func (q *Queries) CountViolationsByPlates(ctx context.Context, dollar_1 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countViolationsByPlates, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createViolation = `-- name: CreateViolation :one
INSERT INTO violations (fine_rule_id, plate_number, officer_id, status, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, fine_rule_id, plate_number, officer_id, status, description, created_at, updated_at
`

type CreateViolationParams struct {
	FineRuleID  uuid.UUID `json:"fine_rule_id"`
	PlateNumber string    `json:"plate_number"`
	OfficerID   uuid.UUID `json:"officer_id"`
	Status      string    `json:"status"`
	Description string    `json:"description"`
}

func (q *Queries) CreateViolation(ctx context.Context, arg CreateViolationParams) (Violation, error) {
	row := q.db.QueryRow(ctx, createViolation,
		arg.FineRuleID,
		arg.PlateNumber,
		arg.OfficerID,
		arg.Status,
		arg.Description,
	)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.FineRuleID,
		&i.PlateNumber,
		&i.OfficerID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getViolationByID = `-- name: GetViolationByID :one
SELECT 
    v.id, v.fine_rule_id, v.plate_number, v.officer_id, v.status, v.description, v.created_at, v.updated_at,
    r.code AS rule_code, r.name AS rule_name, r.description AS rule_description, r.fine_amount, r.version AS rule_version
FROM violations v
JOIN fine_rules r ON v.fine_rule_id = r.id
WHERE v.id = $1
`

type GetViolationByIDRow struct {
	ID              uuid.UUID `json:"id"`
	FineRuleID      uuid.UUID `json:"fine_rule_id"`
	PlateNumber     string    `json:"plate_number"`
	OfficerID       uuid.UUID `json:"officer_id"`
	Status          string    `json:"status"`
	Description     string    `json:"description"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	RuleCode        string    `json:"rule_code"`
	RuleName        string    `json:"rule_name"`
	RuleDescription string    `json:"rule_description"`
	FineAmount      float64   `json:"fine_amount"`
	RuleVersion     int32     `json:"rule_version"`
}

func (q *Queries) GetViolationByID(ctx context.Context, id uuid.UUID) (GetViolationByIDRow, error) {
	row := q.db.QueryRow(ctx, getViolationByID, id)
	var i GetViolationByIDRow
	err := row.Scan(
		&i.ID,
		&i.FineRuleID,
		&i.PlateNumber,
		&i.OfficerID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RuleCode,
		&i.RuleName,
		&i.RuleDescription,
		&i.FineAmount,
		&i.RuleVersion,
	)
	return i, err
}

const listAllViolations = `-- name: ListAllViolations :many
SELECT 
    v.id, v.fine_rule_id, v.plate_number, v.officer_id, v.status, v.description, v.created_at, v.updated_at,
    r.code AS rule_code, r.name AS rule_name, r.description AS rule_description, r.fine_amount, r.version AS rule_version
FROM violations v
JOIN fine_rules r ON v.fine_rule_id = r.id
ORDER BY v.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllViolationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllViolationsRow struct {
	ID              uuid.UUID `json:"id"`
	FineRuleID      uuid.UUID `json:"fine_rule_id"`
	PlateNumber     string    `json:"plate_number"`
	OfficerID       uuid.UUID `json:"officer_id"`
	Status          string    `json:"status"`
	Description     string    `json:"description"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	RuleCode        string    `json:"rule_code"`
	RuleName        string    `json:"rule_name"`
	RuleDescription string    `json:"rule_description"`
	FineAmount      float64   `json:"fine_amount"`
	RuleVersion     int32     `json:"rule_version"`
}

func (q *Queries) ListAllViolations(ctx context.Context, arg ListAllViolationsParams) ([]ListAllViolationsRow, error) {
	rows, err := q.db.Query(ctx, listAllViolations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllViolationsRow{}
	for rows.Next() {
		var i ListAllViolationsRow
		if err := rows.Scan(
			&i.ID,
			&i.FineRuleID,
			&i.PlateNumber,
			&i.OfficerID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RuleCode,
			&i.RuleName,
			&i.RuleDescription,
			&i.FineAmount,
			&i.RuleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViolationsByPlates = `-- name: ListViolationsByPlates :many
SELECT 
    v.id, v.fine_rule_id, v.plate_number, v.officer_id, v.status, v.description, v.created_at, v.updated_at,
    r.code AS rule_code, r.name AS rule_name, r.description AS rule_description, r.fine_amount, r.version AS rule_version
FROM violations v
JOIN fine_rules r ON v.fine_rule_id = r.id
WHERE v.plate_number = ANY($1::VARCHAR[])
ORDER BY v.created_at DESC
LIMIT $2 OFFSET $3
`

type ListViolationsByPlatesParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
}

type ListViolationsByPlatesRow struct {
	ID              uuid.UUID `json:"id"`
	FineRuleID      uuid.UUID `json:"fine_rule_id"`
	PlateNumber     string    `json:"plate_number"`
	OfficerID       uuid.UUID `json:"officer_id"`
	Status          string    `json:"status"`
	Description     string    `json:"description"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	RuleCode        string    `json:"rule_code"`
	RuleName        string    `json:"rule_name"`
	RuleDescription string    `json:"rule_description"`
	FineAmount      float64   `json:"fine_amount"`
	RuleVersion     int32     `json:"rule_version"`
}

func (q *Queries) ListViolationsByPlates(ctx context.Context, arg ListViolationsByPlatesParams) ([]ListViolationsByPlatesRow, error) {
	rows, err := q.db.Query(ctx, listViolationsByPlates, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListViolationsByPlatesRow{}
	for rows.Next() {
		var i ListViolationsByPlatesRow
		if err := rows.Scan(
			&i.ID,
			&i.FineRuleID,
			&i.PlateNumber,
			&i.OfficerID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RuleCode,
			&i.RuleName,
			&i.RuleDescription,
			&i.FineAmount,
			&i.RuleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateViolationStatus = `-- name: UpdateViolationStatus :one
UPDATE violations
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, fine_rule_id, plate_number, officer_id, status, description, created_at, updated_at
`

type UpdateViolationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateViolationStatus(ctx context.Context, arg UpdateViolationStatusParams) (Violation, error) {
	row := q.db.QueryRow(ctx, updateViolationStatus, arg.ID, arg.Status)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.FineRuleID,
		&i.PlateNumber,
		&i.OfficerID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
