// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authdb

import (
	"context"

	"github.com/google/uuid"
)

const countVehiclesByUserID = `-- name: CountVehiclesByUserID :one
SELECT COUNT(*)::bigint
FROM vehicles
WHERE user_id = $1
`

func (q *Queries) CountVehiclesByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVehiclesByUserID, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (user_id, plate_number)
VALUES ($1, $2)
RETURNING id, user_id, plate_number, created_at
`

type CreateVehicleParams struct {
	UserID      uuid.UUID `json:"user_id"`
	PlateNumber string    `json:"plate_number"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle, arg.UserID, arg.PlateNumber)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlateNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :execrows
DELETE FROM vehicles
WHERE id = $1 AND user_id = $2
`

type DeleteVehicleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteVehicle(ctx context.Context, arg DeleteVehicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVehicle, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, user_id, plate_number, created_at
FROM vehicles
WHERE id = $1
`

func (q *Queries) GetVehicleByID(ctx context.Context, id uuid.UUID) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlateNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getVehicleByPlateNumber = `-- name: GetVehicleByPlateNumber :one
SELECT id, user_id, plate_number, created_at
FROM vehicles
WHERE plate_number = $1
`

func (q *Queries) GetVehicleByPlateNumber(ctx context.Context, plateNumber string) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByPlateNumber, plateNumber)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlateNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listVehiclesByUserID = `-- name: ListVehiclesByUserID :many
SELECT id, user_id, plate_number, created_at
FROM vehicles
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVehiclesByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListVehiclesByUserID(ctx context.Context, arg ListVehiclesByUserIDParams) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlateNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
