// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package paymentdb

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (violation_id, amount, status, payment_method, reference_id, error_message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, violation_id, amount, status, payment_method, reference_id, error_message, created_at, updated_at
`

type CreatePaymentParams struct {
	ViolationID   uuid.UUID `json:"violation_id"`
	Amount        float64   `json:"amount"`
	Status        string    `json:"status"`
	PaymentMethod string    `json:"payment_method"`
	ReferenceID   string    `json:"reference_id"`
	ErrorMessage  string    `json:"error_message"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ViolationID,
		arg.Amount,
		arg.Status,
		arg.PaymentMethod,
		arg.ReferenceID,
		arg.ErrorMessage,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.ReferenceID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, violation_id, amount, status, payment_method, reference_id, error_message, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.ReferenceID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByViolationID = `-- name: ListPaymentsByViolationID :many
SELECT id, violation_id, amount, status, payment_method, reference_id, error_message, created_at, updated_at
FROM payments
WHERE violation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByViolationID(ctx context.Context, violationID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByViolationID, violationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ViolationID,
			&i.Amount,
			&i.Status,
			&i.PaymentMethod,
			&i.ReferenceID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
